
all:	compile 

include ../Makefile.env

TARGET			= 

DEPEND_FILES	= 
INC_FILE		= 

CFLAGS 	+= -I./ -I$(INCDIR)

compile: $(TARGET)

$(TARGET): $(DEPEND_FILES)
#	$(AR) $(ARFLAGS) $(TARGET) $?
#	cp -f $(TARGET) $(LIBDIR)
#	cp -f $(INC_FILE)  $(INCDIR)

clean:
#	rm -f $(TARGET) $(DEPEND_FILES)
#	rm -f $(INCDIR)/$(INC_FILE)

